server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    add_header Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob: https: http: http://localhost:9000 http://minio:9000; media-src 'self' blob:; object-src 'self' blob:; frame-src 'self' blob:; connect-src 'self'; font-src 'self'; frame-ancestors 'none';" always;

    # SPA: qualquer rota desconhecida devolve index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy transparente para o backend
    location /api/ {
        proxy_pass         http://backend:8080/api/;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }
}
